[package]
name = "executor"
version = "1.0.0"
authors = []

[addresses]
executor = "_"
endpoint_v2 = "_"
endpoint_v2_common = "_"
layerzero_admin = "_"
layerzero_treasury_admin = "_"
worker_common = "_"
native_token_metadata_address = "0xa"

[dev-addresses]
executor = "0x6001"
endpoint_v2 = "0x13241234"
endpoint_v2_common = "0x9098"
layerzero_admin = "0x18943124"
layerzero_treasury_admin = "0x1894312499"
worker_common = "0x3999"

[dependencies]
endpoint_v2_common = { local = "../../endpoint_v2_common" }
worker_common = { local = "../../worker_peripherals/worker_common" }
