[package]
name = "SimpleMsglibPtbBuilder"
edition = "2024.beta"
version = "0.0.1"

[dependencies]
EndpointPtbBuilder = { local = "../../endpoint-ptb-builder" }
SimpleMessageLib = { local = "../../../message-libs/simple-message-lib" }

[addresses]
simple_msglib_ptb_builder = "0x0"

[dev-dependencies]

[dev-addresses]
