[package]
name = "executor"
version = "1.0.0"
authors = []

[addresses]
executor = "_"
endpoint_v2_common = "_"
endpoint_v2 = "_"
layerzero_admin = "_"
layerzero_treasury_admin = "_"
worker_common = "_"
router_node_0 = "_"
uln_302 = "_"
router_node_1 = "_"
admin_test = "_"
treasury = "_"
msglib_types = "_"
price_feed_router_0 = "_"
price_feed_router_1 = "_"
price_feed_module_0 = "_"
executor_fee_lib_router_0 = "_"
executor_fee_lib_router_1 = "_"
dvn_fee_lib_router_0 = "_"
dvn_fee_lib_router_1 = "_"
executor_fee_lib_0 = "_"
dvn_fee_lib_0 = "_"
native_token_metadata_address = "0x8e4733bdabcf7d4afc3d14f0dd46c9bf52fb0fce9e4b996c939e195b8bc891d9"

[dev-addresses]
executor = "0x6001"
endpoint_v2_common = "0x9098"
endpoint_v2 = "0x12345678"
layerzero_admin = "0x18943124"
layerzero_treasury_admin = "0x1894312499"
worker_common = "0x3999"
router_node_0 = "0x9001"
uln_302 = "0x9005"
router_node_1 = "0x9007"
admin_test = "0x30011"
treasury = "0x123432432"
msglib_types = "0x97324123"
price_feed_router_0 = "0x65DD71A"
price_feed_router_1 = "0x65DD71AB"
price_feed_module_0 = "0x65DD71"
executor_fee_lib_router_0 = "0x30001"
executor_fee_lib_router_1 = "0x30002"
dvn_fee_lib_router_0 = "0x30001a"
dvn_fee_lib_router_1 = "0x30002a"
executor_fee_lib_0 = "0x3000"
dvn_fee_lib_0 = "0x3000a"

[dependencies]
endpoint_v2_common = { local = "../../endpoint_v2_common" }
worker_common = { local = "../../worker_peripherals/worker_common" }
executor_fee_lib_router_0 = { local = "../../worker_peripherals/fee_lib_routers/executor_fee_lib_router_0" }
