[package]
name = "EndpointPtbBuilder"
edition = "2024.beta"
version = "0.0.1"

[dependencies]
EndpointV2 = { local = "../../endpoint-v2" }
PtbMoveCall = { local = "../ptb-move-call" }

[addresses]
endpoint_ptb_builder = "0x0"

[dev-dependencies]

[dev-addresses]
