[package]
name = "OApp"
version = "0.0.1"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move

[dependencies]
EndpointV2 = { local = "../../endpoint-v2" }


[addresses]
oapp = "0x0"

[dev-dependencies]

[dev-addresses]
