[package]
name = "endpoint_v2_common"
version = "1.0.0"

[addresses]
endpoint_v2_common = "_"
endpoint_v2 = "_"
layerzero_admin = "_"
layerzero_treasury_admin = "_"
native_token_metadata_address = "0x8e4733bdabcf7d4afc3d14f0dd46c9bf52fb0fce9e4b996c939e195b8bc891d9"

[dev-addresses]
endpoint_v2_common = "0x9098"
endpoint_v2 = "0x12345678"
layerzero_admin = "0x18943124"
layerzero_treasury_admin = "0x123456231423"

[dependencies.InitiaStdlib]
git = "https://github.com/initia-labs/move-natives.git"
rev = "77d5f3e140143bdaa41f850115b3035c134193e3"
subdir = "initia_stdlib"
