[package]
name = "bridge_remote"
version = "1.0.0"
authors = []

[addresses]
bridge_remote = "_"
bridge_remote_admin = "_"
oft_common = "_"
router_node_0 = "_"
simple_msglib = "_"
blocked_msglib = "_"
uln_302 = "_"
router_node_1 = "_"
endpoint_v2_common = "_"
endpoint_v2 = "_"
layerzero_admin = "_"
layerzero_treasury_admin = "_"
msglib_types = "_"
treasury = "_"
worker_peripherals = "_"
price_feed_router_0 = "_"
price_feed_router_1 = "_"
price_feed_module_0 = "_"
worker_common = "_"
executor_fee_lib_router_0 = "_"
executor_fee_lib_router_1 = "_"
dvn_fee_lib_router_0 = "_"
dvn_fee_lib_router_1 = "_"
executor_fee_lib_0 = "_"
dvn_fee_lib_0 = "_"
dvn = "_"
native_token_metadata_address = "0xa"
# For Initia: "0x8e4733bdabcf7d4afc3d14f0dd46c9bf52fb0fce9e4b996c939e195b8bc891d9"

[dev-addresses]
bridge_remote = "0x302814823"
bridge_remote_admin = "0x12321241"
oft_common = "0x30281482332"
router_node_0 = "0x10000f"
simple_msglib = "0x100011"
blocked_msglib = "0x100001"
uln_302 = "0x100013"
router_node_1 = "0x100010"
endpoint_v2_common = "0x100007"
endpoint_v2 = "0x100006"
layerzero_admin = "0x200001"
layerzero_treasury_admin = "0x200002"
msglib_types = "0x10000b"
treasury = "0x100012"
worker_peripherals = "0x3000"
price_feed_router_0 = "0x10000d"
price_feed_router_1 = "0x10000e"
price_feed_module_0 = "0x10000c"
worker_common = "0x100014"
executor_fee_lib_router_0 = "0x100009"
executor_fee_lib_router_1 = "0x10000a"
dvn_fee_lib_router_0 = "0x100004"
dvn_fee_lib_router_1 = "0x100005"
executor_fee_lib_0 = "0x100008"
dvn_fee_lib_0 = "0x100003"
dvn = "0x100002"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"

[dependencies]
endpoint_v2_common = { git = "https://github.com/LayerZero-Labs/LayerZero-v2", rev = "aptos-v2", subdir = "packages/layerzero-v2/aptos/contracts/endpoint_v2_common" }
endpoint_v2 = { git = "https://github.com/LayerZero-Labs/LayerZero-v2", rev = "aptos-v2", subdir = "packages/layerzero-v2/aptos/contracts/endpoint_v2" }
oft_common = { git = "https://github.com/LayerZero-Labs/LayerZero-v2", rev = "aptos-v2", subdir = "packages/layerzero-v2/aptos/contracts/oapps/oft_common" }

[dev-dependencies]
simple_msglib = { git = "https://github.com/LayerZero-Labs/LayerZero-v2", rev = "aptos-v2", subdir = "packages/layerzero-v2/aptos/contracts/msglib/libs/simple_msglib" }