[package]
name = "layerzero_views"
version = "1.0.0"

[addresses]
layerzero_views = "_"
dvn = "_"
router_node_0 = "_"
zro = "_"
simple_msglib = "_"
blocked_msglib = "_"
uln_302 = "_"
router_node_1 = "_"
endpoint_v2_common = "_"
endpoint_v2 = "_"
layerzero_admin = "_"
layerzero_treasury_admin = "_"
treasury = "_"
msglib_types = "_"
worker_common = "_"
price_feed_router_0 = "_"
price_feed_router_1 = "_"
price_feed_module_0 = "_"
executor_fee_lib_router_0 = "_"
executor_fee_lib_router_1 = "_"
dvn_fee_lib_router_0 = "_"
dvn_fee_lib_router_1 = "_"
executor_fee_lib_0 = "_"
dvn_fee_lib_0 = "_"

[dev-addresses]
layerzero_views = "0x1010123"
dvn = "0x3001"
router_node_0 = "0x9001"
zro = "0x1112"
simple_msglib = "0x9002"
blocked_msglib = "0x9003"
uln_302 = "0x9005"
router_node_1 = "0x9007"
endpoint_v2_common = "0x9098"
endpoint_v2 = "0x12345678"
layerzero_admin = "0x18943124"
layerzero_treasury_admin = "0x1894312499"
treasury = "0x123432432"
msglib_types = "0x97324123"
worker_common = "0x3999"
price_feed_router_0 = "0x65DD71A"
price_feed_router_1 = "0x65DD71AB"
price_feed_module_0 = "0x65DD71"
executor_fee_lib_router_0 = "0x30001"
executor_fee_lib_router_1 = "0x30002"
dvn_fee_lib_router_0 = "0x30001a"
dvn_fee_lib_router_1 = "0x30002a"
executor_fee_lib_0 = "0x3000"
dvn_fee_lib_0 = "0x3000a"

[dependencies.InitiaStdlib]
git = "https://github.com/initia-labs/move-natives.git"
rev = "77d5f3e140143bdaa41f850115b3035c134193e3"
subdir = "initia_stdlib"

[dependencies]
endpoint_v2_common = { local = "../endpoint_v2_common" }
endpoint_v2 = { local = "../endpoint_v2" }
uln_302 = { local = "../msglib/libs/uln_302" }

[dev-dependencies]
dvn = { local = "../workers/dvn" }
treasury = { local = "../treasury" }