[package]
name = "oft_common"
version = "1.0.0"
authors = []

[addresses]
oft_common = "_"
endpoint_v2_common = "_"
endpoint_v2 = "_"
layerzero_admin = "_"
layerzero_treasury_admin = "_"

[dev-addresses]
oft_common = "0x302814823"
endpoint_v2_common = "0x9098"
endpoint_v2 = "0x12345678"
layerzero_admin = "0x18943124"
layerzero_treasury_admin = "0x123456231423"

[dependencies.InitiaStdlib]
git = "https://github.com/initia-labs/move-natives.git"
rev = "77d5f3e140143bdaa41f850115b3035c134193e3"
subdir = "initia_stdlib"

[dependencies]
endpoint_v2_common = { local = "../../endpoint_v2_common" }
