[package]
name = "DvnFeeLib"
edition = "2024.beta"
version = "0.0.1"

[dependencies]
WorkerCommon = { local = "../../worker-common" }
DvnCallType = { local = "../dvn-call-type" }
PriceFeedCallTypes = { local = "../../price-feed-call-types" }

[addresses]
dvn_fee_lib = "0x0"

[dev-dependencies]

[dev-addresses]